name: Python Package using Conda

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update-word-list:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Update the word list
      run: |
        python update_word_list.py
    - name: Commit updated wordlist
      run: |
        git config --global user.name 'nedguthrie'
        git config --global user.email 'nedguthrie@users.noreply.github.com'
        git commit -am "Automated wordlist update"
        git push
